/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "config/Config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HardwareConfig, HardwareConfig, 2)


PB_BIND(SoftwareConfig, SoftwareConfig, AUTO)


PB_BIND(IOConfig, IOConfig, 2)


PB_BIND(UartConfig, UartConfig, AUTO)


PB_BIND(I2CConfig, I2CConfig, AUTO)


PB_BIND(SPIConfig, SPIConfig, AUTO)


PB_BIND(AccelerometerConfig, AccelerometerConfig, AUTO)


PB_BIND(GyroscopeConfig, GyroscopeConfig, AUTO)


PB_BIND(MpuSpiConfig, MpuSpiConfig, AUTO)


PB_BIND(MpuI2cConfig, MpuI2cConfig, AUTO)


PB_BIND(MotorConfig, MotorConfig, AUTO)


PB_BIND(ServoConfig, ServoConfig, AUTO)


PB_BIND(Pin, Pin, AUTO)


PB_BIND(MixerConfig, MixerConfig, 2)


PB_BIND(MixerRule, MixerRule, AUTO)


PB_BIND(RCConfig, RCConfig, AUTO)


PB_BIND(IBUSConfig, IBUSConfig, AUTO)


PB_BIND(CrossfireConfig, CrossfireConfig, AUTO)








