/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "config/Config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HardwareConfiguration, HardwareConfiguration, AUTO)


PB_BIND(BusConfig, BusConfig, AUTO)


PB_BIND(AccelerometerConfig, AccelerometerConfig, AUTO)


PB_BIND(GyroscopeConfig, GyroscopeConfig, AUTO)


PB_BIND(MpuSpiConfig, MpuSpiConfig, AUTO)


PB_BIND(MpuI2cConfig, MpuI2cConfig, AUTO)


PB_BIND(MotorConfig, MotorConfig, AUTO)


PB_BIND(ServoConfig, ServoConfig, AUTO)






